services:
  ml_model:
    image: fpcloud/ml:1.0.0
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: models_${MODEL:-models}
    restart: unless-stopped
    command: >
      bash -c "
        taskiq worker api.broker:broker --workers 8 &
        python3.13 -u -m uvicorn api.server:app --host 0.0.0.0 --port 8000 &
        wait -n
      "
    ports:
      - "${PORT:-8030}:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace/server:/workspace/lib
    volumes:
      - "../local/${MODEL:-models}:/workspace/models"
      - "/Users/rustamkrikbayev/Documents/projects/forecast/ml-server/src:/workspace/server"
      - "/Users/rustamkrikbayev/Documents/projects/forecast/models:/workspace/lib"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 1024M
    tty: true
    stdin_open: true
    networks:
      - ml

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ml

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "${MLFLOW_PORT:-5050}:5000"
    volumes:
      - "../mlruns:/mlflow/mlruns"
    networks:
      - ml

networks:
  ml:
    driver: bridge

volumes:
  redis_data:
