version: "3"
services:
  model-server:
    # Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    image: fpcloud/ml:0.0.1
    ports:
      - 8010:8000
    environment:
      - MODEL_NAME=TI_152
      - MODEL_TYPE=linear
      - MODEL_VERSION=v1
    volumes:
      - /DATASET/project/ml-services/ml-consumption/local/models/KAZ/UZHNIY/JAMBYL/220/L2129/P/:/workspace/model:ro
      - /DATASET/project/ml-services/git/ml-server/src:/workspace/server:ro
    command: python3 -m uvicorn server:app --host 0.0.0.0 --port 8000 --log-level debug
    deploy:
      resources:
        limits:
          memory: 1024m
          cpus: '0.1'


